
  CREATE TABLE "DEV2"."AUTOMATION4" 
   (	"COLUMN1" VARCHAR2(20), 
	"EMAIL1" VARCHAR2(20)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS"